# Generated by Django 4.0.5 on 2022-11-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_alter_rooms_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='size',
            new_name='grade',
        ),
    ]
