# Generated by Django 4.0.5 on 2022-11-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0004_room_delete_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='next_booked_date',
            field=models.DateTimeField(null=True),
        ),
    ]
