# Generated by Django 4.0.5 on 2022-11-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0005_room_next_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='next_booked_date',
            field=models.DateField(null=True),
        ),
    ]
