# Generated by Django 4.0.5 on 2022-11-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0006_alter_room_next_booked_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AddField(
            model_name='room',
            name='next_free_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20)),
                ('guest_name', models.CharField(max_length=100)),
                ('no_of_guests', models.IntegerField()),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('phone_number', models.CharField(max_length=10)),
                ('id_type', models.CharField(choices=[('Ghana Card', 'Ghana Card'), ("Driver's License", "Driver's License"), ("Votter's Id", "Votter's Id")], max_length=20)),
                ('id_number', models.CharField(max_length=30)),
                ('amount_paid', models.FloatField()),
                ('price', models.FloatField()),
                ('room_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionist.room')),
            ],
        ),
    ]
