# Generated by Django 4.0.5 on 2022-11-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0007_remove_room_id_room_next_free_date_alter_room_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
