# Generated by Django 4.0.5 on 2022-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0008_remove_booking_id_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_name',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
