# Generated by Django 4.0.5 on 2022-11-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0011_remove_room_next_booked_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='next_booked_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='next_free_date',
            field=models.DateField(null=True),
        ),
    ]
