# Generated by Django 4.0.5 on 2022-11-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0012_room_next_booked_date_room_next_free_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount_paid',
            field=models.FloatField(null=True),
        ),
    ]
