# Generated by Django 4.0.5 on 2022-11-29 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0014_booking_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20)),
                ('registration', models.IntegerField()),
                ('type_of_car', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_time', models.DateField()),
                ('return_time', models.DateField()),
                ('price', models.FloatField(null=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionist.booking')),
                ('car_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionist.cars')),
            ],
        ),
    ]
