# Generated by Django 4.0.5 on 2022-11-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0015_cars_car_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='registration',
            field=models.CharField(max_length=10),
        ),
    ]
