# Generated by Django 4.0.5 on 2022-12-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0016_alter_cars_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
