# Generated by Django 4.0.5 on 2022-12-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0017_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(null=True, upload_to='room_images'),
        ),
    ]
