# Generated by Django 4.0.5 on 2022-12-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0018_alter_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='room_images'),
        ),
        migrations.AlterField(
            model_name='room',
            name='next_booked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='next_free_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
