# Generated by Django 4.0.5 on 2022-12-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0019_alter_room_img_alter_room_next_booked_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collective_Room',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=200)),
                ('img', models.ImageField(upload_to='room_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='img',
        ),
    ]
