# Generated by Django 4.0.5 on 2022-12-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0020_collective_room_remove_room_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expired',
            field=models.BooleanField(default=True),
        ),
    ]
